### ISSUE TITLE
Ошибка в генераторе 16.12.2018 (recommend)

### ISSUE THREAD

**Issue by recar** [MailRuChamps/hlcupdocs#101]
В микро данных [Пример - 100 записей](https://github.com/MailRuChamps/hlcupdocs/tree/master/data/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20-%20100%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9)

в get_1 есть запрос:
/accounts/62/recommend/?country=Румания&limit=16&query_id=28

И на него ожидается ответ:
{"accounts":[{"fname":"Виталий","sname":"Лебушутев","interests":["Автомобили","Юмор","Шопинг","Сон","Бокс","Гимнастика"],"premium":{"start":1533885480,"finish":1541747880},"status":"свободны","birth":772892119,"id":57,"email":"isareterdetmosbiftit@ymail.com"}]}

Но при этом есть аккаунт с id 15, который тоже из той же страны и подходящего пола. То есть в правильном ответе должны быть два аккаунта 57 и 15

**Comment by recar** [comment]
Похоже отфильтровываются все пользователи у которых нет совпадающих интересов

**Comment by recar** [comment]
похоже в генераторе в рекомендациях считается, что чем больше разница в возрасте тем лучше.
Например [Ещё пример - 100 записей](https://github.com/MailRuChamps/hlcupdocs/tree/master/data/%D0%95%D1%89%D1%91%20%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80%20-%20100%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B5%D0%B9)

В запросе
GET /accounts/62/recommend/?limit=2&query_id=6 HTTP/1.1

Ожидаются 43 и 67 id
В порядке 67, 43
При этом 62 - 1990 года рождения
43 - 1991 года рождения
67 - 1992 года рождения

Совпадает у обоих по одному увлечению. статус и премиум статус одинаковые. Поэтому должно быть 43, 67 в ответе.

И надо обновить правила про обязательное пересечение увлечений.

**Comment by Ivanov-Evgeny** [comment]
Как написал @recar , проблема была связанна с тем, что наличие общих интересов обязательно. Указали это в документации.
