### ISSUE TITLE
docker push : error parsing HTTP 400

### ISSUE THREAD

**Issue by aberkromb** [MailRuChamps/hlcupdocs#105]
docker push не проходит и падает с  ошибкой 

`error parsing HTTP 400 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>400 Bad Request</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
`

**Comment by SannikovDmitry** [comment]
Из лс симтоматика:
Docker version 18.09.0, build 4d60db4
Ос винда 10
первый самый пуш прошел, а вот все последующие нет
первое решение подвисло в статусе Получение из хранилища, с 13.09

**Comment by aberkromb** [comment]
С другой машины и сети все прошло хорошо. Вероятно прокси не пропускал по каким-то причинам.
