### ISSUE TITLE
Ошибка фильтрации в тестовых данных

### ISSUE THREAD

**Issue by nkolosov** [MailRuChamps/hlcupdocs#108]
На запрос 
`/accounts/filter/?birth_gt=690458659&premium_now=1&query_id=983&likes_contains=9629&limit=24`
ожидается пустой ответ `{"accounts":[]}`
Но реально в данных есть пользователи, подходящие под фильтр
`{"accounts":[{"birth":744081950,"id":9300,"premium":{"start":1527211490,"finish":1558747490},"email":"enulesrinalos@ya.ru","likes":["841","2907","1117","3369","331","3957","8085","5835","947","3639","3877","2411","1059","2679","9511","9563","9629","529","5215","2161","7673","8659","3041","5375","371","717","3473","6131","6701","399","5413","9389","4023","4955","8009","2915","1817","4839","7543","4115","8547","8969","6693","271","2593","2373","3361","7715","6449","8427","727","8795","3763","9961","3589","2163","6823","7035","6981","8693","5959","7359","1427","3805","9119","119","8073","9749","8511","4477","6639","7449","6589"]},{"birth":737204032,"id":6394,"premium":{"start":1539612303,"finish":1571148303},"email":"erugmilav@yandex.ru","likes":["8165","3125","6385","1821","991","4127","5133","4657","9059","9441","8689","23","4961","5197","4527","1395","9629","2307","7497"]}]}`

Аналогичная проблема с запросом `/accounts/filter/?premium_now=1&query_id=954&likes_contains=5634&limit=56`

**Comment by jumper423** [comment]
Поддерживаю, у меня такая же ситуация

**Comment by nkolosov** [comment]
Тут, кстати, пишут, что исправлено, но что-то нет =( https://github.com/MailRuChamps/hlcupdocs/issues/96

**Comment by Ivanov-Evgeny** [comment]
@nkolosov напишите пожалуйста название архива с тестовыми данными, которые вы использовали.

**Comment by Ivanov-Evgeny** [comment]
в актуальных данных не должно быть данной проблемы, @nkolosov проблема по прежнему актуальна ?

**Comment by recar** [comment]
В свежих данных все ок с этим
