### ISSUE TITLE
Ошибка в генераторе 19.12.2018 [POST] /accounts/id/

### ISSUE THREAD

**Issue by recar** [MailRuChamps/hlcupdocs#113]
Тяжело точно отдебажить поскольку проявляется в третей фазе и сложно учесть все изменения вручную.

Неправильный запрос третей фазы:
GET	/accounts/group/?order=1&query_id=2500&keys=city%2Cstatus&birth=1988&limit=5	200	{"groups":[{"city":"Амстеранск","status":"всё сложно","count":1},**{"city":"Амстератск","status":"всё сложно","count":1},**{"city":"Амстеринск","status":"всё сложно","count":1},{"city":"Амстеринск","status":"свободны","count":1},{"city":"Амстеровск","status":"всё сложно","count":1}]}

По-моей версии после всех изменений в городе Амстератск не должно быть никого со статусом 'все сложно' 1988 года рождения.

Возможно связано с двумя пост запросами на изменение одного и того же жителя Амстеранска 1988-го года.
POST /accounts/5855/?query_id=684 HTTP/1.1
{"status":"всё сложно","fname":"Олег"}

POST /accounts/5855/?query_id=4080 HTTP/1.1
{"status":"свободны"}

Вероятно, в генераторе есть оптимизация не учитывающая это повторное изменение.

Если вы глянете кто по-вашей версии на третей фазе является жителем Амстератск с 1988-ым годом рождения и статусом 'все сложно' и это не этот персонаж, то напишите, пожалуйста.

**Comment by Ivanov-Evgeny** [comment]
@recar , ваше предположение верно, в ближайшее время исправим

**Comment by recar** [comment]
Судя по всему, post фаза тоже многопоточная. Поэтому, чтобы не было дополнительных рандомных багов при проверке надо зависимые пост запросы разносить хотя бы на время таймауты, то есть при рпс 800 разница должна быть в 1600 запросов.


Зависимые - 
айди лайков и добавление пользователей с этими айди. 
Совпадающие имейлы или телефоны, которые могут вернуть 400 или 200.
Добавление и редактирование одного пользователя.
Повторное редактирование одного пользователя.
