### ISSUE TITLE
Неизвестный город в group (recommend, suggest) 19.12.2018

### ISSUE THREAD

**Issue by stremin** [MailRuChamps/hlcupdocs#114]
В документации сказано, что на неизвестное значение поля (страны и т.п.) ожидается ответ 404.
При этом в тестовых данных для city ожидается 200:

REQUEST  URI: /accounts/group/?city=%D0%9C%D0%BE%D1%81%D0%BE%D1%80%D0%B5%D1%87%D1%81%D0%BA&order=-1&keys=sex&query_id=702&limit=30
REQUEST BODY: <EMPTY>
STATUS GOT: 404 
STATUS EXP: 200
BODY   GOT: <EMPTY>
BODY   EXP: {"groups":[]}

REQUEST  URI: /accounts/4903/recommend/?city=%D0%91%D0%B0%D1%80%D1%81%D0%B5%D0%BB%D0%BE%D0%BD%D0%B0&query_id=158&limit=18
REQUEST BODY: <EMPTY>
STATUS GOT: 404 
STATUS EXP: 200
BODY   GOT: <EMPTY>
BODY   EXP: {"accounts":[]}

REQUEST  URI: /accounts/9018/suggest/?city=%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%BE%D0%BA%D0%B0%D0%BD%D1%81%D0%BA&query_id=664&limit=4
REQUEST BODY: <EMPTY>
STATUS GOT: 404 
STATUS EXP: 200
BODY   GOT: <EMPTY>
BODY   EXP: {"accounts":[]}

**Comment by stremin** [comment]
Аналогично в 20.12.2018

REQUEST  URI: /accounts/group/?city=%D0%A1%D0%B0%D0%BD%D0%BA%D1%82%D0%BE%D0%B2%D0%BE&order=-1&keys=status&query_id=2680&birth=2003&limit=40
REQUEST BODY: <EMPTY>
STATUS GOT: 404 
STATUS EXP: 200
BODY   GOT: <EMPTY>
BODY   EXP: {"groups":[]}

**Comment by recar** [comment]
По-идее логика работы сейчас правильная, а правила надо поправить.

**Comment by recar** [comment]
То, есть просто удалить 'особенность 8' из правил.

**Comment by stremin** [comment]
Не совсем, для country, в отличие от city, ожидается 404:
/accounts/199449/recommend/?query_id=495&limit=16&country=%D0%A0%D0%BE%D1%81%D0%B8%D0%B7%D0%B8%D1%8F	404
