### ISSUE TITLE
При фильтрации по interests, они не ожидаются в результате

### ISSUE THREAD

**Issue by Lanayx** [MailRuChamps/hlcupdocs#115]
test_accounts_201218.zip

REQUEST  URI: /accounts/filter/?limit=20&query_id=72&interests_any=%D0%A2%D0%B0%D0%BD%D1%86%D0%B5%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%2C%D0%93%D0%B0%D1%80%D1%80%D0%B8+%D0%9F%D0%BE%D1%82%D1%82%D0%B5%D1%80
REQUEST BODY:
BODY   GOT: {"accounts":[{"email":"menbiydefhinunun@ymail.com","id":9998,"interests":["Стейк","Солнце","Спортивные машины","Гарри Поттер"]},{"email":"enhilnom@gmail.com","id":9985,"interests":["Танцевальная","Бокс"]},{"email":"fecofraltunopdeh@inbox.ru","id":9983,"interests":["Люди Икс","Юмор","Гарри Поттер","Кинокифильмы","Любовь"]},{"email":"dytatrerarhevnohah@me.com","id":9977,"interests":["Гарри Поттер","Чудак"]},{"email":"tefhusugegnatrewrelin@gmail.com","id":9972,"interests":["Кофе","Танцевальная","Туфли"]},{"email":"iwlichot@gmail.com","id":9951,"interests":["Матрица","Гарри Поттер","Пиво"]},{"email":"ardosebehegyh@list.ru","id":9934,"interests":["Танцевальная","Кинокифильмы","Честность"]},{"email":"helapcaldeaz@ymail.com","id":9917,"interests":["Целоваться","Танцевальная"]},{"email":"bagednasegodry@me.com","id":9899,"interests":["Фитнес","Гарри Поттер","Тяжёлая атлетика"]},{"email":"meriswostial@inbox.ru","id":9893,"interests":["Жизнь","Танцевальная"]},{"email":"rintoserhodasarmusot@me.com","id":9877,"interests":["Новые места","Симпсоны","Гарри Поттер","На открытом воздухе"]},{"email":"hupasbivoat@gmail.com","id":9872,"interests":["Паста","Гарри Поттер"]},{"email":"wogyisetseneli@mail.ru","id":9868,"interests":["Форсаж","Гарри Поттер"]},{"email":"medantefac@icloud.com","id":9867,"interests":["Танцевальная","Рыба"]},{"email":"sococmosedtidmytgeh@inbox.ru","id":9857,"interests":["Фитнес","Танцевальная","Ужин с друзьями","Люди Икс","Фрукты"]},{"email":"lejehahpi@me.com","id":9849,"interests":["Обнимашки","Рэп","Гарри Поттер","Знакомство"]},{"email":"tuhiprasetitihsapes@rambler.ru","id":9826,"interests":["Хип Хоп","YouTube","Гарри Поттер","Курица","South Park","Танцевальная"]},{"email":"enmuhgetiwtatsonan@gmail.com","id":9824,"interests":["Спагетти","Танцевальная","Целоваться","Любовь"]},{"email":"tubintason@mail.ru","id":9812,"interests":["Обнимашки","Танцевальная","Мясо"]},{"email":"altiurtarepefutag@me.com","id":9810,"interests":["Гарри Поттер","Мясо","Фрукты"]}]}
BODY   EXP: {"accounts":[{"id":9998,"email":"menbiydefhinunun@ymail.com"},{"id":9985,"email":"enhilnom@gmail.com"},{"id":9983,"email":"fecofraltunopdeh@inbox.ru"},{"id":9977,"email":"dytatrerarhevnohah@me.com"},{"id":9972,"email":"tefhusugegnatrewrelin@gmail.com"},{"id":9951,"email":"iwlichot@gmail.com"},{"id":9934,"email":"ardosebehegyh@list.ru"},{"id":9917,"email":"helapcaldeaz@ymail.com"},{"id":9899,"email":"bagednasegodry@me.com"},{"id":9893,"email":"meriswostial@inbox.ru"},{"id":9877,"email":"rintoserhodasarmusot@me.com"},{"id":9872,"email":"hupasbivoat@gmail.com"},{"id":9868,"email":"wogyisetseneli@mail.ru"},{"id":9867,"email":"medantefac@icloud.com"},{"id":9857,"email":"sococmosedtidmytgeh@inbox.ru"},{"id":9849,"email":"lejehahpi@me.com"},{"id":9826,"email":"tuhiprasetitihsapes@rambler.ru"},{"id":9824,"email":"enmuhgetiwtatsonan@gmail.com"},{"id":9812,"email":"tubintason@mail.ru"},{"id":9810,"email":"altiurtarepefutag@me.com"}]}

**Comment by recar** [comment]
И не должны по-обновленным правилам

**Comment by recar** [comment]
Также в recommend блоке правил было бы неплохо убрать interests из списка полей, которые надо выводить

**Comment by Lanayx** [comment]
Да, не заметил изменений в правилах =(
