### ISSUE TITLE
Не работает suggest

### ISSUE THREAD

**Issue by Lanayx** [MailRuChamps/hlcupdocs#126]
Данные test_accounts_241218.zip

Запрос /accounts/5687/suggest/?limit=2&city=Варостан&query_id=422

У юзера 5687 нашлось 3 юзера с общими лайками 9903, 7001, 2283, с каждым по одному общему лайку. По формуле из задания победителем выходит 7001, в то время как ответ ожидает 2283.

9903 (Лайк 1126, ts1=1467392247, ts2=1514739716)
2283 (Лайк 1198, ts1=1520464955, ts2=1460774831)
7001 (Лайк 1874, ts1=1478699072, ts2=1497987183)

Видно, что разница таймстемпов лучше всего у 7001

**Comment by recar** [comment]
В данных https://highloadcup.ru/media/condition/test_accounts_251218.zip все suggest запросы на первой фазе у меня сошлись.
