### ISSUE TITLE
Разный ответ для группировки по пустому полю

### ISSUE THREAD

**Issue by ngalaiko** [MailRuChamps/hlcupdocs#129]
В одном случае пустое поле группируется в `null`, в другом просто отсуствтвует

phase 1: `/accounts/group/?limit=25&order=-1&sex=m&keys=country`
<img width="891" alt="screenshot 2018-12-25 at 12 35 41" src="https://user-images.githubusercontent.com/15010292/50421661-4b8e6e00-0842-11e9-8c3e-0c29e5d36f4e.png">

phase 1: `/accounts/group/?limit=45&order=-1&sex=m&keys=country,se`
<img width="903" alt="screenshot 2018-12-25 at 12 35 53" src="https://user-images.githubusercontent.com/15010292/50421662-4b8e6e00-0842-11e9-9ae4-b38048359ad8.png">

**Comment by recar** [comment]
Похоже уже исправленно.
В данных https://highloadcup.ru/media/condition/test_accounts_251218.zip уже нет null-ов.
