### ISSUE TITLE
Ошибка в описании метода /accounts/recommend в данных от 25.12.2018

### ISSUE THREAD

**Issue by stulentsev** [MailRuChamps/hlcupdocs#134]
> Если в ответе оказались одинаково совместимые пользователи (одни и те же status, interests, birth), то выводить их по возрастанию id

Однако же ответы танка ожидают сортировки по __убыванию__ id. Поправьте либо одно, либо другое.

**Comment by recar** [comment]
А в каком запросе ожидается убывание id?

**Comment by stulentsev** [comment]
Хм, перестало воспроизводиться. Как найду evidence - переоткрою.
