### ISSUE TITLE
Добавление лайков в test_accounts_261218

### ISSUE THREAD

**Issue by akrylysov** [MailRuChamps/hlcupdocs#136]
Во второй фазе (query_id=6078) добавляется лайк:
```
{"likee":13912,"liker":24507,"ts":1471106546}
```

Затем в третьей фазе выполняется запрос `/accounts/filter/?interests_any=%D0%9C%D0%B5%D1%82%D0%B0%D0%BB%D0%BB%D0%B8%D0%BA%D0%B0%2C%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%BE%D0%B5+%D0%B2%D0%B8%D0%BD%D0%BE%2C%D0%A2%D0%B5%D0%BB%D0%B5%D0%B2%D0%B8%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5&premium_null=1&query_id=5931&limit=4&likes_contains=13912` на который ожидается ответ:
```
{"accounts":[{"email":"covadda@me.com","id":17579},{"email":"fistyswuconcitinocda@mail.ru","id":13571},{"email":"etesosrassam@rambler.ru","id":8293},{"email":"fehavpisurtohokro@yandex.ru","id":7713}]}
```

Хотя на самом деле ответ должен содержать еще и аккаунт 24507:
```
{"accounts":[{"email":"otwiiral@rambler.ru","id":24507},{"email":"covadda@me.com","id":17579},{"email":"fistyswuconcitinocda@mail.ru","id":13571},{"email":"etesosrassam@rambler.ru","id":8293}]}
```

**Comment by recar** [comment]
Из ответов к этим данным:
POST	/accounts/likes/?query_id=6078	400

То есть этот лайк не должен быть добавлен, поскольку сервер должен вернуть код ошибки в ответ.

**Comment by akrylysov** [comment]
@recar нашел у себя баг, спасибо!
