### ISSUE TITLE
IPC settings: host option

### ISSUE THREAD

**Issue by rayrapetyan** [MailRuChamps/hlcupdocs#26]
Please enable --ipc="host" option when starting a container, otherwise shared memory is not working in my solution...
See https://docs.docker.com/engine/reference/run/#ipc-settings-ipc for reference.
Note: this feature shouldn't affect solutions not using IPC.
Thanks!

**Comment by rayrapetyan** [comment]
Looks like using --ipc="host" is not secure yet, a participant may potentially utilize a whole memory on the host machine. Another run option: --shm-size=8g would work well and is resistant for a host mem vulnerability.

**Comment by kak-tus** [comment]
Мне кажется, что-то не то. Я использую shared memory - у меня работает.
Кроме того, в документации по --ipc="host" написано, что это требуется для IPC между разными контейнерами, а не внутри одного.

**Comment by kak-tus** [comment]
Хотя, в последнем боевом обстреле - shared memory почему-то перестала работать (при этом, работает в тестовом).

**Comment by rayrapetyan** [comment]
По умолчанию там доступно пару десятков МБ (зависит от инстанса, наверно). Я выделяю почти все 8Гб. Но все равно, shmem - стандартный POSIX механизм, должен быть доступен, иначе целый пласт возможных решений отваливается.

**Comment by rayrapetyan** [comment]
В принципе, все это уже не критично - поменял велосипед на мопед у себя в решении..
