### ISSUE TITLE
Количество соединений от танка/phantom

### ISSUE THREAD

**Issue by cdump** [MailRuChamps/hlcupdocs#61]
![2017-08-22-074523_1920x1080_scrot](https://user-images.githubusercontent.com/449375/29549073-855a57f4-870e-11e7-8bfa-547b37073678.png)
Танк/phantom открывает `instances` коннектов и равномерно распределяет нагрузку по ним (не параллельно), хотя для обстрела ему достаточно 1-2 коннектов (что и показывается в консоли с танком, см. скриншот).

Скрины в аттаче, дамп трафика - https://yadi.sk/d/4gEtJpYt3MDZ3R

Вопрос - это его штатное поведение или я что-то делаю не так? Очень похоже, что в бою ситуация точно такая же.
Например, у меня оптимизация под < 10 коннектов, что при выставлении `instances=10` дает огромый прирост скорости (измерял танком), но вот при `instances = 1000` моя оптимизация не работает и соотв. я получаю бОльшее время, хотя танк укладывается и там и там.
![2017-08-22-074436_1920x1080_scrot](https://user-images.githubusercontent.com/449375/29549068-81818c2e-870e-11e7-9e31-0af73f696886.png)

Запуск докера: `docker run -v $(pwd):/var/loadtest --net host -it --rm direvius/yandex-tank -c load/load_3.ini`

На 80 порту висит обычный nginx, с моим серверов ситуация точно такая же.

load_3.ini:
```[phantom]                                                                                                                                                    
address=127.0.0.1
port=80
rps_schedule=line(200, 2000, 120s)

ammo_type=phantom
ammofile=data/FULL/ammo/phase_3_get.ammo
instances = 1000

**Comment by ei-grad** [comment]
Похоже поведение штатное, очевидно сделано чтобы уменьшить влияние времени установки tcp на измерение времени ответа приложения. У меня от танка тоже локально сразу instances коннектов подключается:
```
→ netstat -npt | grep hlcup | wc -l
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
1000
```

**Comment by SannikovDmitry** [comment]
Duplicate of #27
