### ISSUE TITLE
Некорректный вывод с сервера

### ISSUE THREAD

**Issue by mtrempoltsev** [MailRuChamps/hlcupdocs#72]
В приложении пишу отладочную информацию в stdout, но в выводе показываемом сервером иногда пропадают символы:
`building users visits cache... 2s`
Должно быть:
`building users visits cache... 2 ms`

**Comment by xammi** [comment]
Приложите пожалуйста ID решения, где это произошло

**Comment by mtrempoltsev** [comment]
Например, 24471

**Comment by SannikovDmitry** [comment]
Неактуально
