### ISSUE TITLE
POST запросы, оказавшие влияние на провалившиеся GET запросы

### ISSUE THREAD

**Issue by Sammers21** [MailRuChamps/hlcupdocs#77]
Когда на 3 фазе ты видишь GET запрос которые выполнен неудачно, то хотелось бы знать какие POST запросы на 2 фазе оказали влияние на результат который должен был отдать сервер. Так ошибку можно будет хотя-бы воспроизвети.

**Comment by EagleMoor** [comment]
Танком локально тестировали?

**Comment by SannikovDmitry** [comment]
Это хак, так делать не нужно :)
