### ISSUE TITLE
Ускорение работы программы после 42 секунды первой фазы

### ISSUE THREAD

**Issue by oioki** [MailRuChamps/hlcupdocs#78]
На всех моих последних решениях видно падение минимального и суммарного времени ответа после ~42 секунды первой фазы. Это началось с включением keep-alive. Наиболее яркий представитель https://highloadcup.ru/solution/21911/#result
total 29999 &rarr; 19839
![selection_082](https://user-images.githubusercontent.com/1127549/29701808-b9a62dca-8976-11e7-8bed-170d747b7915.png)

Проявляется во всех других решениях:
https://highloadcup.ru/solution/22346/#result
https://highloadcup.ru/solution/21349/#result
https://highloadcup.ru/solution/20774/#result
https://highloadcup.ru/solution/20462/#result
...
https://highloadcup.ru/solution/15612/#result (первое решение с включенным keep-alive)

**Comment by cdump** [comment]
Причина - https://github.com/sat2707/hlcupdocs/issues/61
Говорят, это штатное поведение танка/phantom, у меня на графиках все так же на 1 и 3 фазах.
