### ISSUE TITLE
Не работает рейтинговый обстрел после вчерашнего обновления

### ISSUE THREAD

**Issue by AndrewBurdyug** [MailRuChamps/hlcupdocs#82]
@sat2707 

Сабж, ошибка при попытке запуска рейтингового обстрела: при тестовом  - всё ок, а при боевом - провал на 9 и, как следствие, на 12 этапе. Рейтинговые обстрелы:

> Этап: 9 Окончание обстрела 26.08.2017 11:07:17
> Этап: 12 Анализ полученных результатов 26.08.2017 11:07:21

> Идентификатор решения в системе обстрела ID=23860
> Запущено в рабочем демоне ID=1

Второй раз попробовал(на новой версии своего имеджа) тоже самое: тестовый проходит, рейтинговый валится: 

> Этап: 9 Окончание обстрела 26.08.2017 15:54:56
> Этап: 12 Анализ полученных результатов 26.08.2017 15:54:58

> Идентификатор решения в системе обстрела ID=24227
> Запущено в рабочем демоне ID=12

В чат написал, ребята сказали что тоже такую проблему видят, 
кнопку уведомить тех поддержку нажимали, ждём реакции организаторов....

**Comment by nerro** [comment]
вроде как и тестовый не запускается

**Comment by sat2707** [comment]
А дайте плз id решений, если у вас проблема всё еще повторяется

**Comment by nerro** [comment]
@sat2707, my bad не отписался, посмотрел спустя сутки решение сработало, правда там везде таймаут при всех запросах (решение id=27747)

**Comment by Frank591** [comment]
тестовый висит уже 3,5 часа в ожидании. Уже отключили возможность присылать решения или просто стенд обстрела не справляется?

**Comment by Frank591** [comment]
не выполнились рейтинговых 2 обстрела 30го вечером. Ошибки 
Этап 9: Ошибка при выполнении docker-compose up...
Этап 12: Результаты для анализа не найдены.
Id решений 30798, 30943. Перезапустить сам тоже не могу, т.к. лимит на запуск рейтинговых обстрелов. Перезапустите, пожалуйста обстрел для 30943 хотя бы  - обидно будет так и не узнать результаты(увы, решение, прошедшее тесты, доделал только 30го).

**Comment by Frank591** [comment]
Мои рейтинговые решения так и не перезапустили после ошибки, хотя была новость, что все упавшие решения будут перезапущены. Перезепустите их, пожалуйста! Охото узнать свой результат.

**Comment by SannikovDmitry** [comment]
Неактуально.
