### ISSUE TITLE
Кнопка запуска рейтингового обстрела по расписанию

### ISSUE THREAD

**Issue by evis** [MailRuChamps/hlcupdocs#90]
В идеале с настройкой всех четырёх запусков в сутки. Например, 3:00, 4:00, 15:00, 16:00.

**Comment by EagleMoor** [comment]
Нужно бороться с проблемой, а не искать ее обход =)

Как мне кажется, нужно либо стабилизировать прогоны, либо проводить их несколько параллельно и выдавать средний результат.

**Comment by evis** [comment]
@EagleMoor эта фича не только для того, чтоб в 3 часа ночи запускать. Если, допустим, я временно не дорабатываю код, то зачем мне запускать одно и то же руками, когда можно запускать по расписанию. :) Или хотя бы не по такому расписанию, а просто в самый ранний возможный момент, когда можно запускать, исходя из ограничения 2 запуска/12 часов.

**Comment by EagleMoor** [comment]
Так проблема же все равно не решается. Если увеличить кол-во допустимых рейтинговых обстрелов, что не позволяют выделенные на конкурс сервера, все было бы хорошо.

**Comment by evis** [comment]
@EagleMoor решается проблема запуска одного и того же кода по 4 раза в день руками, зачем это делать руками, когда можно автоматизировать :) Хотя при стабильности прогонов можно один и тот же код тогда и не запускать больше одного раза, это да.

**Comment by SannikovDmitry** [comment]
Не очень значительная фича.
