### ISSUE TITLE
Отправлять письмо о том, что обстрел завершился неудачно

### ISSUE THREAD

**Issue by orangy** [MailRuChamps/hlcupdocs#91]
Мой обстрел упал по непонятной причине, а письмо о неудаче мне не пришло. По всей видимости потому, что анализ данных не сработал, потому что данные не найдены. Я узнал об этом слишком поздно, чтобы вовремя перезапустить обстрел. Ждал письма, думал, что он всё ещё стоит в очереди. Неприятно получилось…

**Comment by etulupov** [comment]
+1

**Comment by xammi** [comment]
Взяли в работу
