### ISSUE TITLE
ИДЕИ

### ISSUE THREAD

**Issue by sat2707** [MailRuChamps/hlcupdocs#94]
Сюда предлагается накидывать идеи на следующее проведение ;)

**Comment by AterCattus** [comment]
Хранимые процедуры/скриптовый язык запросов вместо захардкоженой логики

**Comment by AlexR2D2** [comment]
Дуэль серверов. 
Пишем сервер, который должен "завалить" запросами оппонента и в это же самое время ответить на все его запросы.

**Comment by Lanayx** [comment]
Не совсем идея, но пожелание =) Не считать больше null невалидным полем, но приравнивать к отсутствию поля в json. Иначе это удар по дотнетовским десериализаторам.

**Comment by azaikin** [comment]
Распределенная система. Дано n контейнеров, любой из них может в рандомный момент потухнуть и снова подняться. Между контейнерами пинги в десятки / сотни миллисекунд. POST/GET запросы вперемешку. Большие штрафы за потерянные данные :)

**Comment by azaikin** [comment]
Контест разделен на этапы. В начале каждого этапа в ТЗ появляются новые пункты, иногда они противоречат предыдущим.

**Comment by isergey** [comment]
Повторить условие задачи как в первом раунде. Добавить условия:
1. Для хранения данных использовать общедоступные СУБД: MySQL, PostrgeSQL, Mongo, Tarantool и т.п. Возможно, есть смысл разрешить использовать только одну базу и один кэш. Велосипеды использовать нельзя, так как в реальном мире они почти не работают.
2. Такое же ограничение для веб серверов, хотя тут как получится. 
3. Система должна располагаться в 3 контейнерах. В случае отключения одного или двух контейнеров, система должна продолжить обрабатывать запросы и сохранять информацию. 
4. Обстрел вести по протоколу https используя сжатие gzip.
5. Использовать механизм аутентификации для доступа к сервисам.
6. Добавить запросы по гео индексу.
7. POST GET запросы чередуются.
8. Данные нельзя хранить в памяти. Сделать много данных или мало оперативки.

**Comment by evis** [comment]
Не считать, кто быстрее отдаст ответ, а только ограничить время на ответ. В реальных сервисах обычно есть SLA, которого надо придерживаться, и это не "отдать как можно быстрее", а, например, "99% запросов отдавать за 50 мс". Соответственно, придумать какую-то другую метрику подсчёта результатов вместо суммарного латенси. Предлагаю в таком случае повышать rps, и когда SLA перестанет соблюдаться, завершить фазу (или как там это будет называться в следующем турнире). Кто дольше всех продержался, тот и победил :)

Соответственно, метрикой тогда выступает либо количество времени, которое продержался сервис, ну или максимальный rps, через который он выстоял, суть одна и та же.

**Comment by Frank591** [comment]
Highload это не только(и имхо не столько)про быстрое время ответа. Важные факторы - линейная масшатабируемость и отказоустойчивость.
Собственно предлагается следующая схема:
на входе ваш балансировщик(round-robin), возможность запуска 4 контейнеров через docker-compose и указания на какие из них пойдет трафик с балансировщика. 
Требования:
- любая из нод, принимающих трафик с балансировщика, может быть потушена и затем снова поднята в процессе обстрела.
- смешанные GET и POST с зранее известным процентным распределением(это довольно сильное усложнение касательно текщего профиля обстрела, возможно его стоит вводить во втором раунде или финале).
Считать предлагается, как уже писали выше, перцентиль с заданным временем ответа. 

Не могу говорить за всех, но как мне кажется, текущие соревнования - это соревнования имплементаций хэш-таблиц и джсон сериализаторов в разных ЯП, т.к. запихивание БД в контейнер с приложением крайне геморойное дело, а профит для текущего ТЗ сомнителен. 
Однако в реальных системах положить данные от клиента память, небоясь их потерять, если нода вдруг упадет, можно в крайне узком круге задач. Сответственно возможность запуска 4 контейнеров дает возможность проверять масштабируемость и отказоусточивоать + строить разные схемы для персистентного хранения пользовательских данных (4 аппноды, 3 аппноды + 1 БД, 2 аппнод + 2 БД)

**Comment by ewgRa** [comment]
1. Хотелось бы более детальные описания ограничений на данные.

Например uint32 для id - я думаю встретилась бы сущность с id 4294967295, многие решения бы упали.

Либо описывать ограничения, либо их тестировать.

2. Использовать сервис для общения, который завязан на телефон имхо не лучшее решение. Я так понял в телеграмм давалось много интересной и полезной информации, которая по идее должна была идти в FAQ и транслироваться по email хотя бы.
