### ISSUE TITLE
Ошибка в сгенерированных данных запросов filter и group test_accounts_141218

### ISSUE THREAD

**Issue by recar** [MailRuChamps/hlcupdocs#96]
Похоже на ошибку в генераторе данных.
**Все** GET запросы с likes фильтром ожидают пустое множество групп в ответ.
Несколько примеров из phase_1_get.answ:
```
GET	/accounts/group/?keys=interests&order=1&query_id=861&likes=8020&joined=2018&limit=15	200	{"groups":[]}
GET	/accounts/group/?keys=status&likes=9849&order=-1&query_id=878&limit=20	200	{"groups":[]}

```

Аналогично в  phase_3_get.answ:
```
GET	/accounts/group/?keys=status&likes=630&order=-1&query_id=2000&limit=40	200	{"groups":[]}
GET	/accounts/group/?keys=status&likes=7750&order=-1&query_id=522&birth=1997&limit=20	200	{"groups":[]}

```

**Comment by recar** [comment]
Еще одна ошибка с sname_starts
Генератор проверяет наличие подстроки, а не только начало.

 GET  /accounts/filter/?city_eq=%D0%9B%D0%B5%D1%81%D0%BE%D0%BA%D0%B5%D0%BD%D1%81%D0%BA&sname_starts=%D0%BA%D0%BE%D0%BB&query_id=170&limit=20 
вот этот запрос по-префиксу "кол" ожидает результат СтыКОЛковский

**Comment by SannikovDmitry** [comment]
Исправлено.
