### ISSUE TITLE
Ошибка расчет recommend в сгенрированных данных test_accounts_141218

### ISSUE THREAD

**Issue by recar** [MailRuChamps/hlcupdocs#97]
Например запрос:
```
GET	
/accounts/5799/recommend/?country=%D0%A0%D0%BE%D1%81%D0%B0%D1%82%D1%80%D0%B8%D1%81&query_id=850&limit=2	
200	
{"accounts":[{"premium":{"start":1538336786,"finish":1546199186},"sname":"\u041a\u043b\u0435\u0440\u044b\u043a\u0430\u043a\u043e","email":"hiedhotinbucwosu@rambler.ru","fname":"\u041e\u043b\u044c\u0433\u0430","interests":["\u041a\u0443\u0440\u0438\u0446\u0430","\u041c\u0435\u0442\u0430\u043b\u043b\u0438\u043a\u0430","\u041a\u043b\u0443\u0431\u043d\u0438\u043a\u0430","PS3","\u041d\u043e\u0432\u044b\u0435 \u043c\u0435\u0441\u0442\u0430"],"birth":729712620,"status":"\u0432\u0441\u0451 \u0441\u043b\u043e\u0436\u043d\u043e","id":7006},{"sname":"\u041b\u0443\u043a\u044b\u043a\u0430\u0442\u0438\u043d\u0430","email":"mirhetahuhed@me.com","fname":"\u0412\u0430\u043b\u0435\u0440\u0438\u044f","interests":["\u041a\u0443\u0440\u0438\u0446\u0430","\u041c\u0430\u0441\u0441\u0430\u0436","\u0424\u0438\u043b\u044c\u043c\u044b","\u0424\u0438\u0442\u043d\u0435\u0441"],"birth":638148513,"status":"\u0441\u0432\u043e\u0431\u043e\u0434\u043d\u044b","id":6182}]}

```
Тут фильтр только страна и в данных ожидается один пользователь со статусом "все сложно", а второй без премиум аккаунта.

При этом существует пользователь из той же страны с айди 1300, который свободен и с премиум аккаунтом.

Так же неплохо бы в документации уточнить - разница в возрасте важна в секундах или в годах.

**Comment by DimaGusev** [comment]
И ещё если премиальность стоит выше чем статус то может быть логичнее четвёртый пункт поднять выше первого, чтобы лишней путаницы не было.

**Comment by AnarSultanov** [comment]
> GET	/accounts/7479/recommend/?query_id=832&limit=8	200	

Непонятно почему в результате аккаунт c ID 3704 находится выше чем аккаунт с ID 8650. 

Они оба "свободны", имеют одинаковое количество соппадающих интересов с аккаунтом ID 7479 и у обоих активирован премиум, но таймстамп даты рождения аккаунта с ID 8650 (TS 704295066) ближе к дате рождения аккаунта с ID 7479 (TS 674265494), чем у аккаунта с ID 3704 (TS 728123245), соотвественно аккаунт с ID 8650 должен находиться выше.

**Comment by SannikovDmitry** [comment]
В работе
