### ISSUE TITLE
В документации надо более понятно описать команду suggest

### ISSUE THREAD

**Issue by recar** [MailRuChamps/hlcupdocs#99]
Нераскрытые вопросы:
1. Непонтяно в какой момент применять city, country фильтры. Возможны варианты: 
   а) К пользователям которых мы проверяем на похожии симпатии
   б) Внутри формулы расчета симпатий, чтобы отфильтровывать лайкнутых из других стран
   в) К результирующим рекомендациям, чтобы не советовать пользователей из других стран
   г) некая комбинация из а) б) в)
2. При вычислении похожести как обрабатывать ситуацию, если my_like['ts'] == like['ts'], в этом случае будет деление на ноль и хотелось бы обрабатывать также, как эталонный генератор.
3. При вычислении похожести как обрабатывать, если лайк есть только у одного пользователя. Варианты:
1. Брать дробь 1 / abs(my_like['ts'] - like['ts']) - просто одно из чисел будет 0 и дробь будет 1 / my_like['ts'] или 1/like['ts'].
2. пропускать эту дробь.

Текущее описание:
```
Этот тип запросов похож на предыдущий тем, что он тоже про поиск "вторых половинок". Аналогично пересылается id пользователя, для которого мы ищем вторую половинку и аналогично используется GET-параметер limit. Различия в реализации. Теперь мы ищем, кого лайкают пользователи того же пола с похожими "симпатиями" и предлагаем тех, кого они недавно лайкали сами. В случае, если в запросе передан GET-параметр country или city, то искать "похожие симпатии" нужно только в определённой локации.

Похожесть симпатий определим как функцию: similarity = f (me, account), которая вычисляется однозначно как сумма из дробей 1 / abs(my_like['ts'] - like['ts']), где my_like и like - это симпатии к одному и тому же пользователю. Если общих лайков нет, то стоит считать пользователей абсолютно непохожими с similarity = 0. Если у одного аккаунта есть несколько лайков на одного и того же пользователя с разными датами, то в формуле используется среднее арифметическое их дат.

В ответе возвращается список тех, кого ещё не лайкал пользователь с указанным id, но кого лайкали пользователи с самыми похожими симпатиями. Сортировка по убыванию похожести, а между лайками одного такого пользователя - по убыванию id лайка.
```

**Comment by DimaGusev** [comment]
Было бы полезно ещё привести пример двух пользователей, с несколькими лайками одному и тому же человеку чтобы среднее нужно было считать и несколькими общими лайками, и эталонный ответ который должен получится.

**Comment by zinenko** [comment]
По идее деление на ноль в `1 / abs(my_like['ts'] - like['ts'])` может быть только при абсолютно одновременном лайке. Если уж так случилось, то наверно правильно если результат всей функции `similarity` будет равен 1, то есть максимальная "похожесть".

**Comment by Ivanov-Evgeny** [comment]
1. к пользователям которых мы проверяем на похожии симпатии
2. для my_like['ts'] == like['ts'] заменяем дробь  1 / abs(my_like['ts'] - like['ts']) на 1, укажем это сегодня в документации 
3. нужно пропускать эту дробь
